### ISSUE TITLE
Add OS Architecture to Configuration documentation

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#52]
Add information on the supported OS architecture to the [Configuration](https://github.com/TrivadisPF/modern-data-platform-stack/blob/master/dynamic-stack/Configuration.md) file.

**Comment by ufasoli** [comment]
Should we get the info from the docker images themselves or use the condition in the 'docker-compose.yml.j2' file to know which images support ARM architectures?

**Comment by gschmutz** [comment]
You can relay on the condition in the docker-compose.yml.j2 file. I went through the images on docker-hub to check which ones are supported on ARM and which are not.
